PROVENANCE = {
    "book_id": "prefer-gb-or-fallback",
    "title": "longest",
    "authors": "merge",
    "publisher": "longest",
    "pub_year": "derived",
    "publication_date": "prefer-gb-or-fallback",
    "language": "normalize-prefer-gb",
    "isbn10": "prefer-gb",
    "isbn13": "prefer-gb",
    "num_pages": "max",
    "format": "longest",
    "genres": "merge",
    "rating_value": "max",
    "rating_count": "max",
    "review_count": "max",
    "price": "prefer-gb",
    "current": "prefer-gb-normalize",
    "cover": "prefer-gb",
    "source_winner": "auto",
    "url": "longest",
    "desc": "longest",
    "pub_info": "fallback",
    "review_count_by_lang": "inherit-gr",
    "comments": "inherit-gr"
}
